#!/bin/bash
echo "test0_impl::MY_LOCAL_VAR   = $MY_LOCAL_VAR"
echo "test0_impl::MY_GLOBAL_VAR  = $MY_GLOBAL_VAR"
echo "test0_impl::MY_EXPORT_VAR  = $MY_EXPORT_VAR"
MY_LOCAL_VAR="RESET IT"
MY_GLOBAL_VAR="RESET IT"
MY_EXPORT_VAR="RESET IT"
